### PR TITLE
Dual protobuf

### PR DESCRIPTION
**Pull request by hmaarrfk**
This would really be helpful for me.

See https://github.com/conda-forge/libprotobuf-feedstock/issues/198 https://github.com/conda-forge/tensorflow-feedstock/issues/378 

needless to get my dual opencv builds up and running again:
https://github.com/conda-forge/opencv-feedstock/pull/396

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by ilya-lavrenov — APPROVED** [review]
With static probobuf we had no such issues :D

**Comment by hmaarrfk** [comment]
Tell me about it…..

**Comment by hmaarrfk** [comment]
anyway, i'm excited to see if we can get the openvino runtime working for onnxruntime. not sure if you have any interest in helping on that front!!!!

(Thats my other plan for getting away from tensorflow)

**Comment by ilya-lavrenov** [comment]
> anyway, i'm excited to see if we can get the openvino runtime working for onnxruntime. not sure if you have any interest in helping on that front!!!!

It's a good plan.
I even have a PR to ONNX Runtime repo for simpler cmake integration https://github.com/microsoft/onnxruntime/pull/19184. Once it's merged and released, we can seamlessly integrate OV and ONNX runtime via `find_package(OpenVINO)`.

I have a commit in conda-forge onnx runtime feedstock https://github.com/ilya-lavrenov/onnxruntime-feedstock/commit/54134c1efc25b3930d29ac3c42467e733ed6ea6e which performs such integration.

Do you think we don't need to wait for official ONNX RT releases and can use those patches?

**Comment by hmaarrfk** [comment]
Lets maybe discuss the static protobuf in the most problematic feedstock.
https://github.com/conda-forge/tensorflow-feedstock/issues/378

Other feedstocks have been quite compatible with conda-forge's dynamic linking strategy so its hard to really point to specific problems that dynamic linking brings other than making it difficult to compile tensorflow.

> Do you think we don't need to wait for official ONNX RT releases and can use those patches?

I am much more inclined to merge in a patch that has been 
1. submitted upstream
2. Generally accepted as a good idea by upstream
3. is limited to the build process
4. Helps in dynamic linking and unvendoring from downstream feedstocks ;)

This seems to hit all these points.

There is no exact science, but if you are inclined you can try to see how well it applies to 1.17.1 and hopefully you won't have to do so much work.

**Pull request closed without merging**
