### PR TITLE
Rebuild python312 0 1 hfdf7b7

### PR DESCRIPTION
**Pull request by ilya-lavrenov**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ilya-lavrenov** [comment]
Hi @xhochy @hmaarrfk
Do you have any assumptions what is going wrong? The recipe is untouched, but we errors:
```
   INFO: sysroot: '/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/' files: '['usr/share/man/mann/zero.n', 'usr/share/man/mann/yencode.n', 'usr/share/man/mann/yaml.n', 'usr/share/man/mann/xsxp.n']'
   INFO (libopenvino,lib/openvino-2023.1.0/libopenvino_gapi_preproc.so): lib/libopenvino.2310.dylib found in this package
   INFO (libopenvino,lib/openvino-2023.1.0/libopenvino_gapi_preproc.so): Needed DSO lib/libtbb.12.dylib found in conda-forge::tbb-2021.5.0-hffc8910_5
  ERROR (libopenvino,lib/openvino-2023.1.0/libopenvino_gapi_preproc.so): Needed DSO lib/libc++.1.dylib found in ['libcxx']
  ERROR (libopenvino,lib/openvino-2023.1.0/libopenvino_gapi_preproc.so): .. but ['libcxx'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
   INFO (libopenvino,lib/openvino-2023.1.0/libopenvino_gapi_preproc.so): Needed DSO /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT
   INFO (libopenvino,lib/libopenvino.2023.1.0.dylib): Needed DSO lib/libpugixml.1.dylib found in conda-forge::pugixml-1.14-h13dd4ca_0
   INFO (libopenvino,lib/libopenvino.2023.1.0.dylib): Needed DSO lib/libtbb.12.dylib found in conda-forge::tbb-2021.5.0-hffc8910_5
  ERROR (libopenvino,lib/libopenvino.2023.1.0.dylib): Needed DSO lib/libc++.1.dylib found in ['libcxx']
  ERROR (libopenvino,lib/libopenvino.2023.1.0.dylib): .. but ['libcxx'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
   INFO (libopenvino,lib/libopenvino.2023.1.0.dylib): Needed DSO /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT
   INFO (libopenvino,lib/libopenvino_c.2023.1.0.dylib): lib/libopenvino.2310.dylib found in this package
  ERROR (libopenvino,lib/libopenvino_c.2023.1.0.dylib): Needed DSO lib/libc++.1.dylib found in ['libcxx']
  ERROR (libopenvino,lib/libopenvino_c.2023.1.0.dylib): .. but ['libcxx'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
   INFO (libopenvino,lib/libopenvino_c.2023.1.0.dylib): Needed DSO /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libSystem.B.dylib found in $SYSROOT
```
Looks like a conda issue.

**Comment by xhochy** [comment]
Normally that error is an indicator that you are missing the cxx compiler in build. 🤔

**Comment by xhochy** [comment]
You could try to pin the compiler on osx to version 15. This is the one change that came with the rerender that could actually lead to the error.

**Comment by ilya-lavrenov** [comment]
> You could try to pin the compiler on osx to version 15. This is the one change that came with the rerender that could actually lead to the error.

Unfortunately, it did not help

**Comment by hmaarrfk** [comment]
maybe we need to add a dependency on libcxx https://github.com/conda-forge/libcxx-feedstock/blob/main/recipe/meta.yaml

 I believe we started to get stricter finding libraries that were not declared.

**Comment by hmaarrfk** [comment]
@conda-forge/help-osx-arm64 @conda-forge/clangdev @conda-forge/libcxx (i know there is alot of overlap)

is there is a reason why the libcxx dependency isn't picked up automatically? I'm also hitting the libcxx in https://github.com/conda-forge/shaderc-feedstock/pull/6

**Comment by ilya-lavrenov** [comment]
Ping @conda-forge/help-osx-arm64 @conda-forge/clangdev @conda-forge/libcxx

**Pull request merged**
