### PR TITLE
Fixes for 2023.1.0.dev20230623

### PR DESCRIPTION
**Pull request by artanokhov**

### CODE REVIEW

**Comment by artanokhov** [comment]
@conda-forge-admin, please rerender

**Comment by ilya-lavrenov** [comment]
Already here https://github.com/conda-forge/openvino-feedstock/pull/21 with multiple other improvements

**Comment by artanokhov** [comment]
> let's wait for next pre-release #21 to avoid a lot of packages. Next pre-release contains the state we can advertise to our users.
Windows and Linux aarch64 packages are missing in the previous pre-release 2023.1.0.dev20230623.
So, I suggest incorporating this PR first

Don't see a problem here for our end-users

**Comment by ilya-lavrenov** [comment]
> Don't see a problem here for our end-users

But what are benefits?
Information about pre-release will be available only for upcoming pre-release package. So, even if you update current one - no users will try it.

**Review by ilya-lavrenov — APPROVED** [review]

**Pull request merged**
